/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Filippo Boi
 * Created: 14-gen-2017
 */
CREATE TABLE  Account
(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   saldo DOUBLE PRECISION
);

CREATE TABLE  Acquirente
(
    id  INTEGER GENERATED BY DEFAULT as IDENTITY  PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    mail VARCHAR(128) NOT NULL,
    cognome VARCHAR(128) NOT NULL,
    username VARCHAR(128) NOT NULL,
    indirizzo VARCHAR(128) NOT NULL,
    idConto INTEGER NOT NULL ,
   FOREIGN KEY (idConto) REFERENCES  Account(id)
);

CREATE TABLE  Venditore
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    mail VARCHAR(128) NOT NULL,
    cognome VARCHAR(128) NOT NULL,
    username VARCHAR(128) NOT NULL,
    indirizzo VARCHAR(128) NOT NULL,
    idConto INTEGER NOT NULL ,
   FOREIGN KEY (idConto) REFERENCES  Account(id)
);

CREATE TABLE  Oggetti
(
    id INTEGER GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
    idVenditore INTEGER NOT NULL,
    nomeOggetto VARCHAR(128) NOT NULL,
    descrizione VARCHAR(128) NOT NULL,
    categoria VARCHAR(128) NOT NULL,
    quantita INT NOT NULL,
    prezzoUnita DOUBLE PRECISION NOT NULL,
    indirizzoImg VARCHAR(255) NOT NULL,
    FOREIGN KEY (idVenditore) REFERENCES  Venditore(id)
);

--account insert. 
INSERT INTO Account (SALDO) values 0.00;
INSERT INTO Account (SALDO) values 25.00;
INSERT INTO Account (SALDO) values 500.00;
INSERT INTO Account (SALDO) values 130.00;
INSERT INTO ACCOUNT (SALDO) values 0.00;

--Acquirente insert.
insert into ACQUIRENTE (nome, password,mail, cognome,username, indirizzo, idconto)
VALUES ('Mario', 'casa49', 'mario.rossi@tiscali.it', 'Rossi', 'PorcoRosso', 'via Logudoro ', 3);
insert into ACQUIRENTE (nome, password,mail, cognome,username, indirizzo, idconto)
VALUES ('Giacomo', 'nessunaPietà', 'Giacomo.poretti@gmail.com', 'Poretti', 'Giacomino', 'Viale Colombo 3',2);
insert into ACQUIRENTE (nome, password,mail, cognome,username, indirizzo, idconto)
VALUES ('Paolo', '123456', 'Paolo.Bianchi@yahoo.it', 'Bianchi', 'JeegRobot', 'via Padre Pio 36', 4);

insert into Venditore (nome, password,mail, cognome,username, indirizzo, idconto)
VALUES ('Steve', 'St3v3', 'Stefano.Lavoro@imail.it', 'Lavoro', 'ISteve', 'Piazza Modena 22', 1);
insert into Venditore (nome, password,mail, cognome,username, indirizzo, idconto)
VALUES ('Matteo', 'mamma98', 'Matteo.Mattei@gmail.com', 'Mattei', 'Matteis', 'Viale Colombo 3',5);

insert into Oggetti ( idVenditore, nomeOggetto, descrizione, categoria, quantita, prezzoUnita, indirizzoImg)
Values(1,'Cofanetto Harry Potter','Il cofanetto contiene tutti i libri di Harry Potter, il Best seller che ha incantato generazioni di ragazzi di tutte le età.',
'Film e Serie Tv',100,90.00 , 'http://www.macrolibrarsi.it/data/cop/zoom/h/harry-potter-la-serie-completa-cofanetto-libro-87951-2.jpg');

insert into Oggetti ( idVenditore, nomeOggetto, descrizione, categoria, quantita, prezzoUnita, indirizzoImg)
Values(2,'Monitor LG 4k','potrete vedere ogni dettaglio in questo schermo 31" 4K LG, in grado di mostrare 157 pixel per pollice e colore a 10-bit',
'Periferiche',10,1999.99 , 'http://i.nextmedia.com.au/Utils/ImageResizer.ashx?n=http%3A%2F%2Fi.nextmedia.com.au%2FNews%2FLG+31.jpg&h=338&w=450&c=1');