/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Filippo Boi
 * Created: 14-gen-2017
 */
CREATE DATABASE NERD_HELP;

CREATE TABLE Account(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   saldo DOUBLE PRECISION
);

CREATE TABLE Acquirente(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    mail VARCHAR(128) NOT NULL,
    cognome VARCHAR(128) NOT NULL,
    username VARCHAR(128) NOT NULL,
    indirizzo VARCHAR(128) NOT NULL,
    idConto INTEGER NOT NULL ,
   FOREIGN KEY (idConto) REFERENCES Account(id)
);

CREATE TABLE Venditore
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    mail VARCHAR(128) NOT NULL,
    cognome VARCHAR(128) NOT NULL,
    username VARCHAR(128) NOT NULL,
    indirizzo VARCHAR(128) NOT NULL,
    idConto INTEGER NOT NULL ,
   FOREIGN KEY (idConto) REFERENCES Account(id)
);

CREATE TABLE Oggetti
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idVenditore INTEGER NOT NULL,
    nomeOggetto VARCHAR(128) NOT NULL,
    descrizione VARCHAR(128) NOT NULL,
    categoria VARCHAR(128) NOT NULL,
    quantita INT NOT NULL,
    prezzoUnita DOUBLE PRECISION NOT NULL,
    indirizzoImg VARCHAR(255) NOT NULL,
    FOREIGN KEY (idVenditore) REFERENCES Venditore(id)
);

--Insert--

INSERT INTO Account values 0.00, 500.0, 20.00, 12.00;